[package]
name = "rustlib"
version = "0.1.0"
edition = "2021"

[lib]
name = "rustlib"
crate-type = ["cdylib"]

[dependencies]
rand = "0.8.5"

[dependencies.pyo3]
version = "0.22.2"
features = ["extension-module"]
